### ISSUE TITLE
Not working in version 3.6.1

### ISSUE THREAD

**Issue by liuycy** [svipas/vscode-prettier-plus#14]
Using prettier-eslint@9.0.1 to format code with babel parser for javascript language.

/work/integrated-system/babel.config.js (12/19/2019, 3:00:35 PM):
-----------------------------------------------------------------
Cannot find module 'core-js/modules/es.array.iterator'
Require stack:
- /root/.vscode-server/extensions/svipas.prettier-plus-3.6.1/node_modules/prettier-eslint/dist/index.js
- /root/.vscode-server/extensions/svipas.prettier-plus-3.6.1/dist/main.js
- /root/.vscode-server/bin/9579eda04fdb3a9bba2750f15193e5fafe16b959/out/vs/loader.js
- /root/.vscode-server/bin/9579eda04fdb3a9bba2750f15193e5fafe16b959/out/bootstrap-amd.js
- /root/.vscode-server/bin/9579eda04fdb3a9bba2750f15193e5fafe16b959/out/bootstrap-fork.js

**Comment by liuycy** [comment]
it works when fallbacking to 3.6.0

**Comment by svipas** [comment]
Seems like I fixed #13, but somehow it breaks `prettier-eslint`. I will take a look and today I'm gonna fix it. For now use `3.6.0` version.

**Comment by Flcwl** [comment]
I have a Same problem today.

**Comment by svipas** [comment]
I will fix it today.

**Comment by svipas** [comment]
Should be fixed in `3.6.2` release.

**Comment by Flcwl** [comment]
@svipas  Nice. good!
